-- 2023-06-23
-- 1. 영어영문학과(학과코드 002) 학생들의 학번, 이름, 입학년도 조회 / 입학년도가 빠른순으로 표시
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO AND S.DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

-- 2. 교수 이름 중 3글자 이름이 아닌 교수의 이름과 주민번호 조회하기
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3. 남자 교수들의 이름, 나이를 조회하고 이때 나이가 적은사람이 앞으로 오도록
SELECT PROFESSOR_NAME "교수이름", EXTRACT(YEAR FROM SYSDATE)-1900 - SUBSTR(PROFESSOR_SSN,1,2) "나이"
FROM TB_PROFESSOR
ORDER BY PROFESSOR_SSN DESC;

SELECT PROFESSOR_NAME "교수이름", FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE((SUBSTR(PROFESSOR_SSN, 1, INSTR(PROFESSOR_SSN, '-')-3)+190000), 'YYYYMM')) / 12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY PROFESSOR_SSN DESC;

-- 4. 교수 이름에서 성을 제외한 이름만 출력하기 
SELECT SUBSTR(PROFESSOR_NAME, 2, 3) "이름"
FROM TB_PROFESSOR;

-- 5. 재수생 입학자의 학번, 이름 조회하기
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - (SUBSTR(STUDENT_SSN, 1, INSTR(STUDENT_SSN, '-')-5) + 1900) > 19;

-- 6. 2020년도 12월 25일의 요일 출력받기
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
SELECT TO_CHAR(TO_DATE(20201225), 'DAY')
FROM DUAL;

-- 7. 각각 지정된 날짜의 의미 파악하기
ALTER SESSION SET NLS_DATE_FORMAT = 'YY-MM-DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'RRRR/MM/DD';

SELECT TO_DATE('99/10/11', 'YY/MM/DD')
FROM DUAL;
-- 2099년 10월 11일
SELECT TO_DATE('49/10/11', 'YY/MM/DD')
FROM DUAL;
-- 2049년 10월 11일
SELECT TO_DATE('99/10/11', 'RR/MM/DD')
FROM DUAL;
-- 1999년 10월 11일
SELECT TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;
-- 2049년 10월 11일

-- 8. 대학의 2000년도 이전 입학자들의 학번, 이름 조회하기
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ENTRANCE_DATE < '00-01-01';

-- 9. 한아름의 학점 총 평균
SELECT ROUND(AVG(NVL(POINT, 0)), 1) "평점"
FROM TB_GRADE G, TB_STUDENT S
WHERE G.STUDENT_NO = S.STUDENT_NO AND STUDENT_NAME = '한아름'; 

-- 10. 학과번호와 학과당 학생수 조회하기
SELECT DISTINCT DEPARTMENT_NO "학과번호", COUNT(DEPARTMENT_NO)"학생수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11. 지도 교수를 배정받지 못한 학생의 수 조회하기
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12. 김고운 학생의 년도별 평점 구하기
SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND(AVG(NVL(POINT, 0)), 1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY SUBSTR(TERM_NO, 1, 4);

-- 13. 학과별 휴학생 수 학과번호와 휴학생 수를 조회하기 
SELECT DEPARTMENT_NO "학과 코드명", COUNT(DECODE(ABSENCE_YN, 'Y', 'Y')) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14. 동명이인 학생의 이름과 인원수 조회하기
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
HAVING COUNT(*) > 1
GROUP BY STUDENT_NAME
ORDER BY STUDENT_NAME;

-- 학번 A112113 김고운의 년도, 학기 별 평점과 년도 별 누적 평점, 총 평점을 조회하기 (단, 평점은 소수점 1 자리까지만 반올림하여 표시한다.
SELECT NVL(SUBSTR(TERM_NO, 1, 4), ' ') 년도, NVL(SUBSTR(TERM_NO, 5, 2), ' ') 학기, ROUND(AVG(POINT), 1) 평점 
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113' 
GROUP BY ROLLUP (SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2));