-- 1. 학과명, 계열 표시하기
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2. 학과의 학과 정원 표시하기
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. 국어국문과의 휴학중인 여학생
SELECT DEPARTMENT_NAME "학과 명", DEPARTMENT_NO "학과번호"
FROM TB_DEPARTMENT;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 001 AND ABSENCE_YN = 'Y' AND STUDENT_SSN LIKE '_______2%';

-- 4. 도서관에서 대출 장기연차자들 이름 찾기
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5. 입학정원이 20명~30명인 학과 이름, 계열 조회하기
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6. 총장이름 알아내기
SELECT PROFESSOR_NAME, DEPARTMENT_NO
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7 학과가 지정되지 않은 학생이 있는지 조회하기
SELECT STUDENT_NAME, DEPARTMENT_NO
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8. 선수과목이 존재하는지 그 과목번호가 뭔지 조회하기
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 대학에 어떤 계열이 있는지 조회하기
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10. 02학번 전주 거주자 중 재학중인 학생의 학번, 이름, 주민번호 조회하기
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%' AND ENTRANCE_DATE LIKE '02______' AND ABSENCE_YN = 'N';