-- 2023-06-22
-- 1. 학과명, 계열 표시하기
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2. 학과의 학과 정원 표시하기
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. 국어국문과의 휴학중인 여학생
SELECT DEPARTMENT_NAME "학과 명", DEPARTMENT_NO "학과번호"
FROM TB_DEPARTMENT;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 001 AND ABSENCE_YN = 'Y' AND STUDENT_SSN LIKE '_______2%';

-- 4. 도서관에서 대출 장기연차자들 이름 찾기
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5. 입학정원이 20명~30명인 학과 이름, 계열 조회하기
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6. 총장이름 알아내기
SELECT PROFESSOR_NAME, DEPARTMENT_NO
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7 학과가 지정되지 않은 학생이 있는지 조회하기
SELECT STUDENT_NAME, DEPARTMENT_NO
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8. 선수과목이 존재하는지 그 과목번호가 뭔지 조회하기
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 대학에 어떤 계열이 있는지 조회하기
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10. 02학번 전주 거주자 중 재학중인 학생의 학번, 이름, 주민번호 조회하기
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%' AND ENTRANCE_DATE LIKE '02______' AND ABSENCE_YN = 'N';

-- 2023-06-23
-- 1. 영어영문학과(학과코드 002) 학생들의 학번, 이름, 입학년도 조회 / 입학년도가 빠른순으로 표시
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO AND S.DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

-- 2. 교수 이름 중 3글자 이름이 아닌 교수의 이름과 주민번호 조회하기
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;
-- 세글자가 아닌 교수가 한명이 있다는데 두글자인 사람이과 네글자인 사람의 범위를 생각하지 않아서?

-- 3. 남자 교수들의 이름, 나이를 조회하고 이때 나이가 적은사람이 앞으로 오도록
SELECT PROFESSOR_NAME "교수이름", TO_CHAR(SYSDATE, 'YYYY') - (SUBSTR(PROFESSOR_SSN, 1, INSTR(PROFESSOR_SSN, '-')-5)+1900) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY PROFESSOR_SSN DESC;

-- 4. 교수 이름에서 성을 제외한 이름만 출력하기 
SELECT SUBSTR(PROFESSOR_NAME, 2, 3) "이름"
FROM TB_PROFESSOR
ORDER BY PROFESSOR_NO;

-- 5. 재수생 입학자의 학번, 이름 조회하기
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - (SUBSTR(STUDENT_SSN, 1, INSTR(STUDENT_SSN, '-')-5) + 1900) > 19;

-- 6. 2020년도 12월 25일의 요일 출력받기
SELECT TO_CHAR(TO_DATE(20201225), 'DAY')
FROM DUAL;

-- 7. 각각 지정된 날짜의 의미 파악하기
ALTER SESSION SET NLS_DATE_FORMAT = 'YY-MM-DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'RRRR/MM/DD';

SELECT TO_DATE('99/10/11', 'YY/MM/DD')
FROM DUAL;
-- 2099년 10월 11일
SELECT TO_DATE('49/10/11', 'YY/MM/DD')
FROM DUAL;
-- 2049년 10월 11일
SELECT TO_DATE('99/10/11', 'RR/MM/DD')
FROM DUAL;
-- 1999년 10월 11일
SELECT TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;
-- 2049년 10월 11일

-- 8. 대학의 2000년도 이전 입학자들의 학번, 이름 조회하기
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
WHERE ENTRANCE_DATE < '00-01-01';

-- 9. 한아름의 학점 총 평균
SELECT ROUND(AVG(NVL(POINT, 0)), 1) "평점"
FROM TB_GRADE G, TB_STUDENT S
WHERE G.STUDENT_NO = S.STUDENT_NO AND STUDENT_NAME = '한아름'; 

-- 10. 학과번호와 학과당 학생수 조회하기
SELECT DISTINCT DEPARTMENT_NO "학과번호", COUNT(DEPARTMENT_NO)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11. 지도 교수를 배정받지 못한 학생의 수 조회하기
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12. 김고운 학생의 년도별 평점 구하기
SELECT TERM_NO "년도", CLASS_NO, POINT
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
