CREATE TABLE MEMBER(

USER_NO NUMBER PRIMARY KEY,
USER_ID VARCHAR2(20) NOT NULL,
USER_PW VARCHAR2(20) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,
USER_ADDR VARCHAR(50) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_MEMBER;