-- 회원가입
CREATE TABLE MEMBER (
    MEM_ID VARCHAR2(30),
    ADM_ID VARCHAR2(30),
    MEM_PW VARCHAR2(30) NOT NULL,
    MEM_NICK VARCHAR2(30),
    MEM_NAME VARCHAR2(30) NOT NULL,
    MEM_ADR VARCHAR2(100) NOT NULL,
    MEM_PHONE VARCHAR2(30) NOT NULL,
    MEM_GENDER CHAR(10) CHECK(STATUS IN ('남성', '여성')) NOT NULL,
    MEM_EMAIL VARCHAR2(30),
    MEM_DATE DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT MEMBER_MEMBER_NO_PK PRIMARY KEY(MEM_ID)
);

COMMENT ON COLUMN MEMBER.MEM_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.ADM_ID IS '관리자아이디';
COMMENT ON COLUMN MEMBER.MEM_PW IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NICK IS '회원닉네임';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.MEM_ADR IS '회원주소';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '회원연락처';
COMMENT ON COLUMN MEMBER.MEM_GENDER IS '성별(남성/여성)';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '회원이메일';
COMMENT ON COLUMN MEMBER.MEM_DATE IS '회원가입일';

-- 회원정보
CREATE TABLE MEMBER_INFO (
    MEM_GRADE VARCHAR2(30),
    POINT NUMBER,
    POINT_GRADE NUMBER
);

COMMENT ON COLUMN MEMBER_INFO.MEM_GRADE IS '회원등급';
COMMENT ON COLUMN MEMBER_INFO.POINT IS '적립포인트';
COMMENT ON COLUMN MEMBER_INFO.POINT_GRADE IS '포인트적립률';

-- 게시판
CREATE TABLE BULLETIN (
    BULT_NO NUMBER,
    BULT_TITLE VARCHAR2(50),
    BULT_DATE DATE DEFAULT SYSDATE,
    BULT_WRITER VARCHAR2(30),
    BULT_CONT CLOB,
    BULT_REPLY NUMBER,
    BULT_VIEW NUMBER
);

COMMENT ON COLUMN BULLETIN.BULT_NO IS '게시글번호';
COMMENT ON COLUMN BULLETIN.BULT_TITLE IS '제목';
COMMENT ON COLUMN BULLETIN.BULT_DATE IS '작성일자';
COMMENT ON COLUMN BULLETIN.BULT_WRITER IS '작성자';
COMMENT ON COLUMN BULLETIN.BULT_CONT IS '내용';
COMMENT ON COLUMN BULLETIN.BULT_VIEW IS '조회수';
COMMENT ON COLUMN BULLETIN.BULT_REPLY IS '댓글수';

-- 후기게시판
CREATE TABLE REVIEW_BULT (
    RE_BULT_NO NUMBER,
    RE_BULT_TITLE VARCHAR2(50),
    RE_BULT_DATE DATE DEFAULT SYSDATE,
    RE_BULT_WRITER VARCHAR2(30),
    RE_BULT_CONT CLOB,
    RE_BULT_REPLY NUMBER,
    RE_BULT_VIEW NUMBER,
    RE_AUCTION_NO NUMBER
);

COMMENT ON COLUMN BULLETIN.RE_BULT_NO IS '(후기게시판)게시글번호';
COMMENT ON COLUMN BULLETIN.RE_BULT_TITLE IS '(후기게시판)제목';
COMMENT ON COLUMN BULLETIN.RE_BULT_DATE IS '(후기게시판)작성일자';
COMMENT ON COLUMN BULLETIN.RE_BULT_WRITER IS '(후기게시판)작성자';
COMMENT ON COLUMN BULLETIN.RE_BULT_CONT IS '(후기게시판)내용';
COMMENT ON COLUMN BULLETIN.BULT_VIEW IS '(후기게시판)조회수';;;
COMMENT ON COLUMN BULLETIN.RE_BULT_REPLY IS '(후기게시판)댓글수';
COMMENT ON COLUMN BULLETIN.RE_AUCTION_NO IS '(후기게시판)구매물품번호';
